# Generated by Django 4.1 on 2022-08-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("descriptions", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="static")),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
